### ISSUE TITLE
[Bug]: In the navbar the active state is not changing 

### ISSUE THREAD

**Issue by aashishx03** [pankaj-coder47/React-Portfolio#1]
## Describe the bug

- In the navbar, the active state is not changing while toggling the sections.

## To Reproduce

- Go to home page
- Select about or any other section 
- You'll find the bug

## Expected behaviour 

- The active status should change when we change the sections

**Comment by git-dhanji** [comment]
**Thanks Brother **

**Comment by git-dhanji** [comment]
#1 Thanks you brother
